# Generated by Django 4.0.5 on 2022-06-05 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Meeting Description', max_length=255)),
                ('document', models.FileField(upload_to='meetings/documents/')),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Published Date')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Special'), (2, 'Regular')], null=True)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-publish'],
            },
        ),
    ]
