# Generated by Django 4.0.4 on 2022-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingdocument',
            name='department',
            field=models.CharField(choices=[('AFFILIATIONS', 'Head, Affiliations'), ('HEAD', 'Head, Academic and Student Affairs')], max_length=13),
        ),
    ]
