# Generated by Django 4.0.4 on 2022-06-01 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_incomingdocument_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingdocument',
            old_name='sent_by',
            new_name='sender',
        ),
    ]
