# Generated by Django 4.0.4 on 2022-06-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
