# Generated by Django 4.0.4 on 2022-06-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0002_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-date_of_request'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_request',
            field=models.PositiveIntegerField(verbose_name='Number Of Request'),
        ),
    ]
