# Generated by Django 4.0.5 on 2022-06-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_requests', '0003_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_received',
            field=models.DateTimeField(blank=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='request',
            name='received',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='received_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Received By'),
        ),
    ]
